name: CI


on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install
        
      - name: gatsby build&deploy
        run : npm run deploy
        
